name: petpooja
description: PetPooja - full project with firebase OTP login
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

  # Other
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  http: ^1.5.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
